language: go
go_import_path: github.com/sirupsen/logrus
git:
  depth: 1
env:
  - GO111MODULE=on
go: 1.15.x
os: linux
install:
  - ./travis/install.sh
script:
  - go run mage.go -v crossBuild
  - go run mage.go lint
  - export GOMAXPROCS=4
  - export GORACE=halt_on_error=1
  - go test -race -v ./...
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then go test -race -v -tags appengine ./... ; fi
